### PR TITLE
LPS-109713 Regen

### PR DESCRIPTION
**Pull request by inacionery**
Hey @barrosdennys,

These changes broke some Poshi tests, could you please fix them? 

Thanks!

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test:workflow

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
ci:test:sf

**Comment by barrosdennys** [comment]
Just started reviewing :)

**Comment by barrosdennys** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86055.

**Pull request closed without merging**
