### PR TITLE
LRQA-57026 Moving Workflow team related tests from portal-web to modules and disabling flaky/failing tests

### PR DESCRIPTION
**Pull request by barrosdennys**

### CODE REVIEW

**Comment by barrosdennys** [comment]
ci:test:sf

**Comment by barrosdennys** [comment]
ci:test:relevant

**Comment by barrosdennys** [comment]
ci:test:stable

**Comment by barrosdennys** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Pull request merged**
