### PR TITLE
LRQA-51773 Fixing poshi tests and removing Kaleo Designer tests from relevant until the icons are correctly displayed

### PR DESCRIPTION
**Pull request by barrosdennys**

### CODE REVIEW

**Comment by barrosdennys** [comment]
ci:test:relevant

**Comment by barrosdennys** [comment]
ci:test:sf

**Comment by barrosdennys** [comment]
@alexcandidos would you please review it?

**Comment by alexcandidos** [comment]
Hi @barrosdennys , the changes are okay!

**Comment by barrosdennys** [comment]
ci:test:relevant

**Pull request closed without merging**
