### PR TITLE
master-qa-53628-1

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-53628

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by barrosdennys** [comment]
ci:test:workflow

**Comment by barrosdennys** [comment]
Just started reviewing :)

**Comment by barrosdennys** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82841. [See changes here.](https://github.com/barrosdennys/liferay-portal/compare/eed3da00c0dd~1...eed3da00c0dd)

**Pull request closed without merging**
