### PR TITLE
LRQA-51450 Automate adding SLA to Single Approver in poshi

### PR DESCRIPTION
**Pull request by barrosdennys**

### CODE REVIEW

**Comment by barrosdennys** [comment]
ci:test:sf

**Comment by barrosdennys** [comment]
ci:test:relevant

**Comment by barrosdennys** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@barrosdennys @alexcandidos thank you for adding this test, this is very needed.

I can't find this test result in Testray. I think EE tests will only run if you send another PR to master-private and reference this PR URL in `git-commit-portal`. [example](https://github.com/jpince/liferay-portal-ee/pull/60/commits/b72a695ca06693d26b1c5f8e08ffb901879255b0)
[Testray results for this pull](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=734563467)
[Testray results for pull to BChan](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=734550984&testrayCaseTypeId=101949)

@barrosdennys also, if you are sending a PR to yourself to test something specific, you make a test commit in `test.properties` like the example below. This will use fewer CI server resources and reduce the time to get results (due to fewer tests running). Then just drop that commits before forwarding to BChan.
[example if running ci:test:relevant](https://github.com/jpince/liferay-portal/pull/116/commits/97fb3b552bab7f1a668a5e9aba01b55148bd3b31)
[example if running ci:test](https://github.com/jpince/liferay-portal/pull/119/commits/372e2349791956e71674987af10347efd6dd1cbe) < note only building tomcat

cc/ @palomaanunes @manoelcyreno so you are aware of this information as well

**Pull request closed without merging**
